#!/usr/bin/env python3
"""Generate an outreach sequence using AI prompts and user's voice.

Usage:
  python3 generate_sequence.py --channel email --steps 3 \
    --voice context/my-voice.md --offer context/my-offer.md \
    --icp context/my-icp.md --output .tmp/sequence.json

This script generates the sequence STRUCTURE (steps, timing, subjects).
The actual message bodies are generated by Claude using the prompt templates.

Output: JSON with {success, sequence}
"""

import argparse
import json
import os
import sys

CHANNEL_DEFAULTS = {
    'email': {
        'max_steps': 5,
        'day_spacing': [0, 3, 7, 14, 21],
        'types': ['initial', 'followup', 'followup', 'value', 'breakup'],
        'prompt_prefix': 'cold_email',
    },
    'instagram': {
        'max_steps': 3,
        'day_spacing': [0, 2, 5],
        'types': ['initial', 'followup', 'breakup'],
        'prompt_prefix': 'instagram_dm',
    },
    'linkedin': {
        'max_steps': 3,
        'day_spacing': [0, 3, 7],
        'types': ['initial', 'followup', 'breakup'],
        'prompt_prefix': 'linkedin_dm',
    },
    'whatsapp': {
        'max_steps': 2,
        'day_spacing': [0, 3],
        'types': ['initial', 'followup'],
        'prompt_prefix': 'whatsapp',
    },
}


def load_context(path: str) -> str:
    """Load a context file if it exists."""
    if not path or not os.path.exists(path):
        return ''
    with open(path) as f:
        return f.read()


def generate_sequence(channel: str, steps: int, name: str,
                      voice: str, offer: str, icp: str) -> dict:
    """Generate a sequence structure."""
    defaults = CHANNEL_DEFAULTS.get(channel)
    if not defaults:
        return {'success': False, 'error': f'Unknown channel: {channel}'}

    steps = min(steps, defaults['max_steps'])
    prefix = defaults['prompt_prefix']

    sequence_steps = []
    for i in range(steps):
        step_type = defaults['types'][i] if i < len(defaults['types']) else 'followup'
        day = defaults['day_spacing'][i] if i < len(defaults['day_spacing']) else defaults['day_spacing'][-1] + 7

        step = {
            'step': i + 1,
            'day': day,
            'type': step_type,
            'prompt_file': f'skills/outreach/assets/prompts/{prefix}_{step_type}.txt',
            'condition': 'no_reply' if i > 0 else None,
        }

        # Email-specific fields
        if channel == 'email':
            if step_type == 'initial':
                step['subject_template'] = '{{lead.name}} — pregunta rápida sobre {{lead.business}}'
            elif step_type == 'followup':
                step['subject_template'] = 'Re: pregunta rápida'
            elif step_type == 'breakup':
                step['subject_template'] = 'Último intento, {{lead.first_name}}'
            elif step_type == 'value':
                step['subject_template'] = '{{lead.first_name}}, esto te puede interesar'

        sequence_steps.append(step)

    return {
        'success': True,
        'sequence': {
            'name': name,
            'channel': channel,
            'total_steps': steps,
            'steps': sequence_steps,
            'context': {
                'voice_file': voice if voice else None,
                'offer_file': offer if offer else None,
                'icp_file': icp if icp else None,
            },
            'personalization_tags': [
                '{{lead.name}}', '{{lead.first_name}}', '{{lead.last_name}}',
                '{{lead.business}}', '{{lead.email}}', '{{lead.city}}',
                '{{lead.website}}', '{{lead.phone}}',
            ],
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--channel', required=True,
                        choices=list(CHANNEL_DEFAULTS.keys()),
                        help='Outreach channel')
    parser.add_argument('--steps', type=int, default=3,
                        help='Number of steps in sequence (default: 3)')
    parser.add_argument('--name', default=None,
                        help='Campaign name (auto-generated if not provided)')
    parser.add_argument('--voice', default='context/my-voice.md',
                        help='Path to voice context file')
    parser.add_argument('--offer', default='context/my-offer.md',
                        help='Path to offer context file')
    parser.add_argument('--icp', default='context/my-icp.md',
                        help='Path to ICP context file')
    parser.add_argument('--output', default=None,
                        help='Output file path')
    args = parser.parse_args()

    name = args.name or f'{args.channel}_sequence_{args.steps}steps'
    result = generate_sequence(args.channel, args.steps, name,
                               args.voice, args.offer, args.icp)

    out_str = json.dumps(result, indent=2, ensure_ascii=False)

    if args.output:
        os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)
        with open(args.output, 'w') as f:
            f.write(out_str)
        print(json.dumps({
            'success': True,
            'output_file': args.output,
            'channel': args.channel,
            'steps': result['sequence']['total_steps'],
        }))
    else:
        print(out_str)


if __name__ == '__main__':
    main()
